FROM node:20.18-alpine

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies including dev dependencies
RUN pnpm install

# We don't need to COPY . . here because we're using volumes in docker-compose
COPY . .

EXPOSE 3000

# Use nodemon for development
CMD ["pnpm", "start"]
