version: '3.8'
services:
  #app:
    #build:
      #context: .
      #dockerfile: Dockerfile.dev
    #ports:
      #- "3000:3000"
    #env_file:
      #- .env
    #depends_on:
      #- redis
  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
